sonar.projectKey=calculator-demo
sonar.projectName=Calculator Demo

sonar.sources=app
sonar.tests=test

sonar.test.inclusions=test/**/*.py

sonar.exclusions=venv/**,.scannerwork/**,__pycache__/**

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml